dependencies {
    // Registrate
    api(libs.registrate)

    // Anvil Lib
    implementation(libs.anvillib)
    interfaceInjectionData(libs.anvillib)

    // AnvilCraft
    implementation(libs.anvilcraft) { transitive = false }
    interfaceInjectionData(libs.anvilcraft) { transitive = false }

    // JEI
    compileClasspath(libs.jei.common.api) { transitive = false }
    compileClasspath(libs.jei.forge.api) { transitive = false }
    compileClasspath(libs.jei.forge) { transitive = false }
    runtimeClasspath(libs.jei.forge) { transitive = false }

}