dependencies {
    // Anvil Lib
    runtimeOnly(libs.anvillib)
    compileOnly(libs.bundles.anvillib)
    interfaceInjectionData(libs.anvillib.recipe)
    interfaceInjectionData(libs.anvillib.moveableEntityBlock)

    // AnvilCraft
    implementation(libs.anvilcraft) { transitive = false }
    interfaceInjectionData(libs.anvilcraft) { transitive = false }

    // JEI
    compileClasspath(libs.jei.common.api) { transitive = false }
    compileClasspath(libs.jei.forge.api) { transitive = false }
    compileClasspath(libs.jei.forge) { transitive = false }
    runtimeClasspath(libs.jei.forge) { transitive = false }

}