# Jvm info
java_version=21
org.gradle.jvmargs=-Xmx2G
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=true
## Environment info
minecraft_version=1.21.1
minecraft_version_range=[1.21.1,1.22)
neo_version=21.1.152
neo_version_range=[21,)
loader_version_range=[4,)
parchment_minecraft_version=1.21.1
parchment_mappings_version=2024.11.17
## Upload info
upload=false
modrinth_id=xxxxx
## Mod info
mod_id=anvilcraft_simple_processing
mod_name=AnvilCraft SimpleProcessing
mod_license=MIT
mod_version=0.1.0
maven_group=com.renzaifei.asp
mod_authors=renzaifei
mod_description=This mod provides a more convenient processing method.
